---
title: "HGMA_Processing"
output: html_document
date: "2025-12-24"
---

```{r}
rm(list=ls()) 
source("Function_Helpers.R")
req_pkgs = c('dplyr', 'mixOmics', 'curatedMetagenomicData', 'SummarizedExperiment', 
             'stringr', 'testthat', 'tibble', 'stringr', 'purrr', 'readxl')

install_if_missing(req_pkgs)
```

```{r}
sample_md = read_excel("sample_metadata.xlsx")
## changed to read excel
abund_data = read_excel("vect_atlas.xlsx")
corr_taxa = read.csv("corresponding_taxa.csv")

## preprocessing 1st round
corr_taxa <- corr_taxa %>%
  filter(!str_detect(name, "unclassified"))

# contains taxa whose name ends in space + digit
multi_taxa <- corr_taxa %>%
  filter(str_detect(name, "\\s\\d$"))

# removes the digit
multi_taxa <- multi_taxa %>%
  mutate(name = str_sub(name, 1, -3)) 

# new list of unique taxa from the ones with trailing numbers
multi_taxa_lst <- unique(multi_taxa$name)

```

```{r}
dataset_study = "PRJEB1786"
#dataset_study = "PRJNA422434"
```

```{r}
# list of disease to be kept
disease_arr = c("T2D", "Healthy", "NGT", "healthy")
# subsets metadata to only include the rows that are part of the dataset study matched by the bioproject column
metadata <- sample_md[sample_md$BioProject == dataset_study, ]
# filter by disease
metadata = metadata %>% 
  filter(Disease %in% disease_arr)
sp_id = metadata$sample.ID
# filter the columns of abund data to include include samples with the selected diseases
## changed the syntax of this line because in R the column name is not "X"
rawdata <- abund_data[, c(colnames(abund_data)[1], sp_id)]
# replaces taxa codes with taxa names 
## Changed name from rawdata to merged raw for testing. 
merged_raw <- merge(
  rawdata,
  corr_taxa,
  ## changed to 1
  by.x = 1,
  by.y = "id",
  all.x = TRUE  # all.x=TRUE: Keep all rows from x even if no matching key in y (left join)
)
##changed code to just drop the first column because the column name is not always X
merged_raw <- merged_raw[, -1] 
merged_raw <- merged_raw[!is.na(merged_raw$name), ]  # drop the NaN value in 'name' column

```
```{r}
library(dplyr)
```

```{r}

# get a list of merged taxa names
taxa_lst = merged_raw$name

# transpose data
rawdata_v1 <- merged_raw |>
  dplyr::select(-name) |>
  t() |>
  as.data.frame(check.names = FALSE)

colnames(rawdata_v1) = taxa_lst
# transforming the index  column to sample id grabbing from the rownames
##changed code for clarity
rawdata_v1$sample_id <- rownames(rawdata_v1)
rownames(rawdata_v1) <- NULL

rawdata_v1 = merge(rawdata_v1, 
                   metadata[, c("sample.ID", "Disease")], 
                   by.x="sample_id", 
                   by.y="sample.ID",
                   all.x=TRUE)
View(rawdata_v1)
names(rawdata_v1)[names(rawdata_v1) == "Blautia coccoides == Blautia producta"] = "Blautia producta"
dim(rawdata_v1)
```

```{r}
check_main_species <- function(lst) {
  integers <- as.character(1:9)
  for (sub in lst) {
    last_char <- substr(sub, nchar(sub), nchar(sub))
    if (!(last_char %in% integers)) {
      return(TRUE)
    }
  }
  return(FALSE)
}

for (taxa in multi_taxa_lst) {
  if ( !grepl("subtype", tolower(taxa), fixed = T) ) {
    cols = colnames(rawdata_v1)
    rawdata_v1$taxa = 0
    alltaxa_columns <- cols[grepl(taxa, cols, fixed = T)]
    
    if ( length(alltaxa_columns) == 1 ) {
      rawdata_v1[[taxa]] <- rawdata_v1[[alltaxa_columns[1]]]
    } else if ( check_main_species(alltaxa_columns) == T ) {
      alltaxa_columns <- setdiff(alltaxa_columns, taxa)
      rawdata_v1 <- rawdata_v1[, !(names(rawdata_v1) %in% alltaxa_columns), drop = FALSE]
      
    } else {
      rawdata_v1[[taxa]] <- rowSums(rawdata_v1[, alltaxa_columns, drop = FALSE], na.rm = TRUE)
      rawdata_v1 <- rawdata_v1[, !(names(rawdata_v1) %in% alltaxa_columns), drop = FALSE]
    }
  }
}

dim(rawdata_v1)
saveRDS(rawdata_v1, "p_test")
```

```{r}
# schemal level feature alignment
p_selected <-readRDS("p_selected")
# clean colnames
colnames(p_selected) <- sub("^species:\\s*", "", colnames(p_selected), ignore.case = TRUE)
# loop through p_test column names, and only for columns that contain /, check if any p_selected name is fully contained in that column name. If yes, rename it to the p_selected name and record the mapping; otherwise, leave it.

# Initialize list to store old -> new column name mappings
changed_colnames <- list()

# Loop through each column in p_test
for (i in seq_along(colnames(p_test))) {
  col_name <- colnames(p_test)[i]
  
  # Only process columns that contain '/'
  if (grepl("/", col_name, fixed = TRUE)) {
    
    for (sel_name in colnames(p_selected)) {

      if (grepl(sel_name, col_name, fixed = TRUE)) {
        print("match found")
        #** instead of getting the first instance of the name just rename the list to all of the matched names
        colnames(p_test)[i] <- sel_name
        changed_colnames[[col_name]] <- sel_name
        break  # stop at first match
      }
    }
  }
}

# Mapping list of old -> new column names
changed_colnames

# get rawdata_v1
overlap_cols <- intersect(colnames(p_test), colnames(p_selected)) # Find the intersection with p_test column names

# Subset p_test to only include these columns
rawdata_v1 <- p_test[, overlap_cols, drop = FALSE]

# Optional: check results
dim(rawdata_v1)
"Firmicutes bacterium CAG:95" %in% colnames(rawdata_v1)
"Proteobacteria bacterium CAG:139" %in% colnames(rawdata_v1)


## summary of changes made
# in this case p_select is from the training set with individual filtering
# some issue with CMD columns spacing changed into full stops:
# --> added check.name =FALSE to all check.data.frame in function helpers and full_framework so that the CMD names are not change
# --> deleted 'species:' prefix in CMD colnames
# renaming logic: checks if the full string of p_test is in p_select changes p_test to the first instance of p_select name found. 
# documents name changes in vector changed_colanmes
```

```{r}
rename_map <- c(
  "Lachnospiraceae bacterium hRUG904 / Clostridiales bacterium RUG495 / [Clostridium] sp. CAG:127" = "[Clostridium] sp. CAG:127",
  "Firmicutes bacterium CAG:65 / [Clostridium] sp. 2789STDY5608883" = "Firmicutes bacterium CAG:65",
  "Lachnospiraceae bacterium CIM:MAG 844 / Firmicutes bacterium CAG:95" = "Firmicutes bacterium CAG:95",
  "[Ruminococcus] sp. CAG:17 / Blautia sp. 2789STDY5608880" = "[Ruminococcus] sp. CAG:17",
  "Roseburia sp. CAG:100 / Lachnospiraceae bacterium CIM:MAG 54" = "Roseburia sp. CAG:100",
  "Clostridiales bacterium UBA7273 / Firmicutes bacterium CAG:240" = "Firmicutes bacterium CAG:240",
  "Firmicutes bacterium CAG:24 / [Clostridium] sp. 2789STDY5834869 & 2789STDY5834922" = "Firmicutes bacterium CAG:24",
  "Coprococcus sp. 2789STDY5608819 / [Clostridium] sp. CAG:264" = "[Clostridium] sp. CAG:264",
  "[Ruminococcus] sp. 2789STDY5608794 & sp. 2789STDY5834890 / Firmicutes bacterium CAG:56" = "Firmicutes bacterium CAG:56",
  "Lachnospiraceae bacterium TF01-11 / [Clostridium] sp. CAG:122" = "[Clostridium] sp. CAG:122",
  "[Acinetobacter] sp. N54.MGS-139 / Proteobacteria bacterium CAG:139" = "Proteobacteria bacterium CAG:139",
  "[Ruminococcus] sp. CAG:60 / Blautia sp. 2789STDY5608836" = "[Ruminococcus] sp. CAG:60",
  "[Eubacterium] sp. CAG:251 / [Clostridium] sp. A254.MGS-251" = "[Eubacterium] sp. CAG:251",
  "[Clostridium] sp. CAG:217 / Clostridiales bacterium CIM:MAG 317_1" = "[Clostridium] sp. CAG:217",
  "Lachnoclostridium sp. SNUG30386 / [Clostridium] sp. CAG:43" = "[Clostridium] sp. CAG:43",
  "[Ruminococcaceae] bacterium D16 / Clostridiales bacterium Choco116" = "[Ruminococcaceae] bacterium D16",
  "Firmicutes bacterium CAG:41 / [Clostridium] sp. 2789STDY5834935 & sp. 2789STDY5608853" = "Firmicutes bacterium CAG:41",
  "[Clostridiaceae] bacterium CIM:MAG 755 / [Clostridium] sp. CAG:230" = "[Clostridium] sp. CAG:230",
  "Firmicutes bacterium CAG:212 / [Clostridium] sp. 2789STDY5834871" = "Firmicutes bacterium CAG:212",
  "Bacteroidales bacterium H2 / [Prevotella] sp. CAG:251" = "[Prevotella] sp. CAG:251",
  "Ruminococcaceae bacterium UBA1821 / [Clostridium] sp. CAG:678" = "[Clostridium] sp. CAG:678",
  "Oscillibacter sp. ER4 / Firmicutes bacterium CAG:129_59_24" = "Oscillibacter sp. ER4",
  "Clostridiales bacterium RUG303 & RUG439 & RUG453 / Firmicutes bacterium CAG:129" = "Firmicutes bacterium CAG:129",
  "Candidatus Methanomethylophilus alvus / Methanoculleus sp. CAG:1088" = "Methanoculleus sp. CAG:1088",
  "[Clostridiaceae] bacterium CIM:MAG 987 / [Clostridium] sp. CAG:533" = "[Clostridium] sp. CAG:533",
  "[Firmicutes] bacterium CIM:MAG 721 / [Bacillus] sp. CAG:988" = "[Bacillus] sp. CAG:988", 
  "Disease" = "disease"
)

cols <- colnames(rawdata_v1)
hits <- cols %in% names(rename_map)
cols[hits] <- unname(rename_map[cols[hits]])
colnames(rawdata_v1) <- cols

rawdata_v1
```






```{r}
hgma_lst = list(abund=subset(rawdata_v1, select=-c(sample_id, disease)), meta=subset(rawdata_v1, select=c(sample_id, disease)) )
# calculate the second smallest value
x <- unlist(hgma_lst$abund)
x <- x[x > 0]
second_smallest <- sort(unique(x), na.last = NA)[2]

processed_lst = preprocess_single(meta=hgma_lst$meta, abund=hgma_lst$abund, diseases=disease_arr, 
                                 keep_cols=c("sample_id"), offset_value=second_smallest, percent=0.01, CLR=T )

names(processed_lst)[names(processed_lst) == "data"] = "abund"
```

```{r}
names(processed_lst)[]
```






## function
parameters
study_name: BioProject code in HGMA
threshold_for_LowCountsRm: 0.01% default
```{r}
draw_TestSet = function(threshold_for_LowCountsRm=0.01, disease_lst=c("T2D", "Healthy", "NGT", "healthy"), dataset_study) {
  # ingest rawdata
  ### should this be normalised to all csv files?
  print("Reading HGMA rawdata...")
  sample_md = read_excel("sample_metadata.xlsx")
  # added the excel file in
  abund_data = read_excel("vect_atlas.xlsx")
  # webscraped data of species id and name
  ### how will users be able to access this?
  corr_taxa = read.csv("corresponding_taxa.csv")
  
  ## Preprocessing 1st round
  print("Processing metadata and rawdata...")
  corr_taxa <- corr_taxa %>% 
    filter(!str_detect(name, "unclassified"))
  
  # Collapse number-suffixed taxa names into a single base taxon
  multi_taxa <- corr_taxa %>% 
    filter(str_detect(name, "\\s\\d$"))
  
  multi_taxa <- multi_taxa %>%
    mutate(name = str_sub(name, 1, -3))
  
  multi_taxa_lst <- unique(multi_taxa$name)
  print(multi_taxa_lst)
  # Subset metadata by study and disease, then extract sample IDs
metadata <- sample_md %>%
  filter(
    BioProject == dataset_study,
    Disease %in% disease_lst
  )
sp_id <- metadata$sample.ID
  
  # Subset rawdata by study and disease using extraced sampled IDs
  rawdata <- abund_data[, c(colnames(abund_data)[1], sp_id)]
  View(rawdata)
# replace taxa codes with taxa names 
rawdata <- merge(
  rawdata,
  corr_taxa,
  ## changed to 1
  by.x = 1,
  by.y = "id",
  all.x = TRUE  # all.x=TRUE: Keep all rows from x even if no matching key in y (left join)
)
##changed code to just drop the first column because the column name is not always X
rawdata <- rawdata[, -1] 
# drop NAs
rawdata <- rawdata[!is.na(rawdata$name), ]
# get a list of merged taxa names for tranposing data
# Transpose numeric abundance only
taxa_lst <- rawdata$name
rawdata_abund <- rawdata[, setdiff(colnames(rawdata), "name")]
rawdata_v1 <- t(rawdata_abund) |> as.data.frame(check.names = FALSE)
colnames(rawdata_v1) <- taxa_lst
rawdata_v1$sample_id <- rownames(rawdata_v1)
rownames(rawdata_v1) <- NULL

# Rename the 'Disease' column in rawdata_v1 to lowercase 'disease'
View(rawdata_v1)

# add sample id and disease columns to rawdata to create rawdata_v1
rawdata_v1 = merge(rawdata_v1, 
                   metadata[, c("sample.ID", "Disease")], 
                   by.x="sample_id", 
                   by.y="sample.ID",
                   all.x=TRUE)
# make disease lowercase
colnames(rawdata_v1)[colnames(rawdata_v1) == "Disease"] <- "disease"

# Rename exceptional merged taxon to standardize name
names(rawdata_v1)[names(rawdata_v1) == "Blautia coccoides == Blautia producta"] = "Blautia producta"
  
# Function to check if any column name in a list does NOT end with a numeric suffix
check_main_species <- function(lst) {
  integers <- as.character(1:9)  # digits 1-9 as character for comparison
  for (sub in lst) {
    last_char <- substr(sub, nchar(sub), nchar(sub))  # last character of the string
    if (!(last_char %in% integers)) {                # if last char is NOT a digit
      return(TRUE)                                  # return TRUE: main species exists
    }
  }
  return(FALSE)                                     # all names end with digits → no main species
}


# Loop through taxa that originally had numeric suffixes
for (taxa in multi_taxa_lst) {
  
  # Skip taxa that are subtypes (contain 'subtype' in their name)
  if (!grepl("subtype", tolower(taxa), fixed = TRUE)) {
    
    cols <- colnames(rawdata_v1)       # all column names in the abundance table
    rawdata_v1$taxa <- 0               # temporary placeholder column for aggregation
    alltaxa_columns <- cols[grepl(taxa, cols, fixed = TRUE)]  # find all columns matching this taxa
    
    if (length(alltaxa_columns) == 1) {
      # Only one column corresponds to this taxa → just copy it to the base taxa name
      rawdata_v1[[taxa]] <- rawdata_v1[[alltaxa_columns[1]]]
      
    } else if (check_main_species(alltaxa_columns) == TRUE) {
      # Multiple columns exist and main species is present
      # Remove numeric-suffixed columns, keeping only the main species column
      alltaxa_columns <- setdiff(alltaxa_columns, taxa)  
      rawdata_v1 <- rawdata_v1[, !(names(rawdata_v1) %in% alltaxa_columns), drop = FALSE]
      
    } else {
      # Multiple columns exist, but no main species column
      # Aggregate all numeric-suffixed columns into a single column
      rawdata_v1[[taxa]] <- rowSums(rawdata_v1[, alltaxa_columns, drop = FALSE], na.rm = TRUE)
      # Remove original numeric-suffixed columns after aggregation
      rawdata_v1 <- rawdata_v1[, !(names(rawdata_v1) %in% alltaxa_columns), drop = FALSE]
    }
  }
}
  
# standardise ambiguous multi-species labels (eg. "B. fragilis/B. vulgatus") by assigning htem to corresponding species in the training set

### why do we assume that the true species is the one in the training dataset? Would this introduce uncertainties in biological interpretation?

# p_selected in CMD training data after forward selection
p_selected <-readRDS("p_selected")
colnames(p_selected) <- sub("^species:\\s*", "", colnames(p_selected), ignore.case = TRUE)
rawdata_v1

# loop through rawdata_v1 column names, and only for columns that contain /, check if any p_selected name is fully contained in that column name. If yes, rename it to the p_selected name and record the mapping; otherwise, leave it.

# Initialize list to store old -> new column name mappings
changed_colnames <- list()

# Loop through each column in rawdata_v1 keeps sample_id and Disease cols
for (i in seq_along(colnames(rawdata_v1))) {
  col_name <- colnames(rawdata_v1)[i]
  # Skip columns that should not be modified
  if (col_name %in% c("sample_id", "disease")) {
    next  # skip this iteration
  }
  # Only process columns that contain '/'
  if (grepl("/", col_name, fixed = TRUE)) {
    
    for (sel_name in colnames(p_selected)) {

      if (grepl(sel_name, col_name, fixed = TRUE)) {
        print("match found")
        colnames(rawdata_v1)[i] <- sel_name
        changed_colnames[[col_name]] <- sel_name
        break  # stop at first match
      }
    }
  }
}

# Mapping list of old -> new column names
print(changed_colnames)
# get rawdata_v1
overlap_cols <- intersect(colnames(rawdata_v1), colnames(p_selected)) # Find the intersection with rawdata_v1 column names

# Subset rawdata_v1 to only include these columns
#rawdata_v1 <- rawdata_v1[, overlap_cols, drop = FALSE]

# Optional: check results
dim(rawdata_v1)

  print("Organizing the metadata and the rawdata into proper output form")
  hgma_lst = list(abund=subset(rawdata_v1, select=-c(sample_id, disease)), meta=subset(rawdata_v1, select=c(sample_id, disease)) )
  # calculate the second smallest value
  x <- unlist(hgma_lst$abund)
  x <- x[x > 0]
  second_smallest <- sort(unique(x), na.last = NA)[2]
  processed_lst = preprocess_single(meta=hgma_lst$meta, abund=hgma_lst$abund, diseases=disease_lst, 
                                   keep_cols=c("sample_id"), offset_value=second_smallest, percent=0.01, CLR=T )
  names(processed_lst)[names(processed_lst) == "data"] = "abund"
  processed_lst$meta$study = dataset_study
  
  return(processed_lst)
}
```

```{r}
testset1 = draw_TestSet(dataset_study="PRJEB1786")
#testset2 = draw_TestSet(dataset_study="PRJNA422434")

```





# Draw individual testing set out
```{r}
sample_md = read_excel("sample_metadata.xlsx")
## changed to read excel
abund_data = read_excel("vect_atlas.xlsx")
corr_taxa = read.csv("corresponding_taxa.csv")

## Preprocessing 1st round
corr_taxa <- corr_taxa %>%
  filter(!str_detect(name, "unclassified"))

multi_taxa <- corr_taxa %>%
  filter(str_detect(name, "\\s\\d$"))

multi_taxa <- multi_taxa %>%
  mutate(name = str_sub(name, 1, -3))

multi_taxa_lst <- unique(multi_taxa$name)

dataset_study = "PRJEB1786"
# dataset_study = "PRJNA422434"

disease_arr = c("T2D", "Healthy", "NGT", "healthy")
metadata = as.data.frame(sample_md[sample_md['BioProject'] == dataset_study, ])
metadata = metadata %>% 
  filter(Disease %in% disease_arr)
sp_id = metadata$sample.ID


rawdata <- abund_data[, c(colnames(abund_data)[1], sp_id)]
# replaces taxa codes with taxa names 
## Changed name from rawdata to merged raw for testing. 
rawdata <- merge(
  rawdata,
  corr_taxa,
  ## changed to 1
  by.x = 1,
  by.y = "id",
  all.x = TRUE  # all.x=TRUE: Keep all rows from x even if no matching key in y (left join)
)
##changed code to just drop the first column because the column name is not always X
rawdata <- rawdata[, -1] 
rawdata <- rawdata[!is.na(rawdata$name), ]  # drop the NaN value in 'name' column


taxa_lst = rawdata$name
rawdata_v1 = data.frame(t(rawdata[, !(names(rawdata) %in% c("name"))]))
colnames(rawdata_v1) = taxa_lst
names(rawdata_v1)[names(rawdata_v1) == "index"] = "sample_id"
rawdata_v1$sample_id = rownames(rawdata_v1)

check_main_species <- function(lst) {
  integers <- as.character(1:9)
  for (sub in lst) {
    last_char <- substr(sub, nchar(sub), nchar(sub))
    if (!(last_char %in% integers)) {
      return(TRUE)
    }
  }
  return(FALSE)
}

for (taxa in multi_taxa_lst) {
  if ( !grepl("subtype", tolower(taxa), fixed = T) ) {
    cols = colnames(rawdata_v1)
    rawdata_v1$taxa = 0
    alltaxa_columns <- cols[grepl(taxa, cols, fixed = T)]
    
    if ( length(alltaxa_columns) == 1 ) {
      rawdata_v1[[taxa]] <- rawdata_v1[[alltaxa_columns[1]]]
    } else if ( check_main_species(alltaxa_columns) == T ) {
      alltaxa_columns <- setdiff(alltaxa_columns, taxa)
      rawdata_v1 <- rawdata_v1[, !(names(rawdata_v1) %in% alltaxa_columns), drop = FALSE]
      
    } else {
      rawdata_v1[[taxa]] <- rowSums(rawdata_v1[, alltaxa_columns, drop = FALSE], na.rm = TRUE)
      rawdata_v1 <- rawdata_v1[, !(names(rawdata_v1) %in% alltaxa_columns), drop = FALSE]
    }
  }
}

'''
rename_map <- c(
  "Lachnospiraceae bacterium hRUG904 / Clostridiales bacterium RUG495 / [Clostridium] sp. CAG:127" = "[Clostridium] sp. CAG:127",
  "Firmicutes bacterium CAG:65 / [Clostridium] sp. 2789STDY5608883" = "Firmicutes bacterium CAG:65",
  "Lachnospiraceae bacterium CIM:MAG 844 / Firmicutes bacterium CAG:95" = "Firmicutes bacterium CAG:95",
  "[Ruminococcus] sp. CAG:17 / Blautia sp. 2789STDY5608880" = "[Ruminococcus] sp. CAG:17",
  "Roseburia sp. CAG:100 / Lachnospiraceae bacterium CIM:MAG 54" = "Roseburia sp. CAG:100",
  "Clostridiales bacterium UBA7273 / Firmicutes bacterium CAG:240" = "Firmicutes bacterium CAG:240",
  "Firmicutes bacterium CAG:24 / [Clostridium] sp. 2789STDY5834869 & 2789STDY5834922" = "Firmicutes bacterium CAG:24",
  "Coprococcus sp. 2789STDY5608819 / [Clostridium] sp. CAG:264" = "[Clostridium] sp. CAG:264",
  "[Ruminococcus] sp. 2789STDY5608794 & sp. 2789STDY5834890 / Firmicutes bacterium CAG:56" = "Firmicutes bacterium CAG:56",
  "Lachnospiraceae bacterium TF01-11 / [Clostridium] sp. CAG:122" = "[Clostridium] sp. CAG:122",
  "[Acinetobacter] sp. N54.MGS-139 / Proteobacteria bacterium CAG:139" = "Proteobacteria bacterium CAG:139",
  "[Ruminococcus] sp. CAG:60 / Blautia sp. 2789STDY5608836" = "[Ruminococcus] sp. CAG:60",
  "[Eubacterium] sp. CAG:251 / [Clostridium] sp. A254.MGS-251" = "[Eubacterium] sp. CAG:251",
  "[Clostridium] sp. CAG:217 / Clostridiales bacterium CIM:MAG 317_1" = "[Clostridium] sp. CAG:217",
  "Lachnoclostridium sp. SNUG30386 / [Clostridium] sp. CAG:43" = "[Clostridium] sp. CAG:43",
  "[Ruminococcaceae] bacterium D16 / Clostridiales bacterium Choco116" = "[Ruminococcaceae] bacterium D16",
  "Firmicutes bacterium CAG:41 / [Clostridium] sp. 2789STDY5834935 & sp. 2789STDY5608853" = "Firmicutes bacterium CAG:41",
  "[Clostridiaceae] bacterium CIM:MAG 755 / [Clostridium] sp. CAG:230" = "[Clostridium] sp. CAG:230",
  "Firmicutes bacterium CAG:212 / [Clostridium] sp. 2789STDY5834871" = "Firmicutes bacterium CAG:212",
  "Bacteroidales bacterium H2 / [Prevotella] sp. CAG:251" = "[Prevotella] sp. CAG:251",
  "Ruminococcaceae bacterium UBA1821 / [Clostridium] sp. CAG:678" = "[Clostridium] sp. CAG:678",
  "Oscillibacter sp. ER4 / Firmicutes bacterium CAG:129_59_24" = "Oscillibacter sp. ER4",
  "Clostridiales bacterium RUG303 & RUG439 & RUG453 / Firmicutes bacterium CAG:129" = "Firmicutes bacterium CAG:129",
  "Candidatus Methanomethylophilus alvus / Methanoculleus sp. CAG:1088" = "Methanoculleus sp. CAG:1088",
  "[Clostridiaceae] bacterium CIM:MAG 987 / [Clostridium] sp. CAG:533" = "[Clostridium] sp. CAG:533",
  "[Firmicutes] bacterium CIM:MAG 721 / [Bacillus] sp. CAG:988" = "[Bacillus] sp. CAG:988", 
  "Disease" = "disease"
)

cols <- colnames(rawdata_v1)
hits <- cols %in% names(rename_map)
cols[hits] <- unname(rename_map[cols[hits]])
colnames(rawdata_v1) <- cols
'''



## should make sure the index/rownames is the sample_id for both metadata and abundance matrix
rownames(rawdata_v1) = rawdata_v1$sample_id
rawdata_v1$sample_id = NULL
rownames(metadata) = metadata$sample.ID
names(metadata)[names(metadata) == "Disease"] = "disease"


obj = list(abund = rawdata_v1, 
           meta = metadata)
saveRDS(obj, file = paste0(dataset_study, ".rds"))
```


```{r}
metadata$sample.ID
```































